apiVersion: v1
kind: Pod
metadata:
  name: hello-kubecon
  namespace: default
  labels:
    app: hello-kubecon
spec:
  containers:
  - name: hello-kubecon
    image: fillerink/kubecon-india-talk:hello-kubecon
    ports:
    - containerPort: 5000


