apiVersion: v1
kind: Pod
metadata:
  name: "kubecon-india-talk-demo"
  namespace: default
  labels:
    app: "kubecon-india-talk-demo"
spec:
  containers:
  - name: flask-app
    image: "fillerink/kubecon-india-talk"
    ports:
    - containerPort: 5000
      name: http


